In [1]:
import torch
import torch.nn as nn
from gensim.models import KeyedVectors
import wasp

In [2]:
n2v = wasp.NodeEmbedding(str(wasp.get_data_path("sem_graph", "node2vec_sem_graph.pkl")))

In [3]:
emb = n2v.get_n2v_embedding_layer()

In [4]:
stoi = n2v.stoi

In [5]:
import wasp
import json
with open(wasp.get_data_path("item_pool", "item_pool_supp.json"), "r", encoding="UTF-8") as fin:
    items = json.load(fin)

In [6]:
from functools import partial

In [9]:
n2v_encode = partial(n2v.encode, max_length=2, drop_unk=True)

In [10]:
n2v_encode("今天/怎麼樣/由2於/呢".split("/"))

[889, 13690]

In [23]:
n2v.model.wv.vector_size

100

In [17]:
A = torch.rand(5,1,4)
pool = nn.MaxPool1d(4)
pool(A)

tensor([[[0.8583]],

        [[0.8965]],

        [[0.9091]],

        [[0.8060]],

        [[0.7299]]])

In [18]:
qlen = []
for item_x in items:
    qs = sum([1 for x in item_x["question"] if x in n2v.vocab])
    olen = []
    for opt_x in item_x["options"]:
        os = sum([1 for x in opt_x if x in n2v.vocab])
        olen.append(os)
    qs = qs + max(olen)
    qlen.append(qs)
max(qlen)

43

In [14]:
indices = torch.tensor([stoi(x) for x in "今天/天氣/真好/珠江".split("/")])
emb(indices)
indices

tensor([  889,  2605,  6428, 15600])

In [12]:
indices

tensor([ 889, 2605, 6428])

In [6]:
model = KeyedVectors.load(str(wasp.get_data_path("sem_graph", "node2vec_sem_graph.pkl")))

In [32]:
model.wv.vocab.get("大生", -1)

-1

In [13]:
model.wv.vectors.shape

(15600, 100)

In [14]:
emb_weights = torch.FloatTensor(model.wv.vectors)

In [16]:
embedding = nn.Embedding.from_pretrained(emb_weights)

In [45]:
n2v = torch.FloatTensor(model.wv.vectors)
unk = torch.rand([1, n2v.shape[-1]])
weights = torch.stack([n2v, unk], axis=1)
weights.shape

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 15600 and 1 in dimension 0 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:612

In [53]:
torch.cat([n2v, unk], axis=0).shape

torch.Size([15601, 100])

In [21]:
embedding(torch.LongTensor([1,2,3]))

tensor([[ 2.3375e-01, -4.2155e-01,  7.2261e-01, -9.8861e-02,  1.0304e+00,
         -2.9366e+00, -8.6833e-01,  1.3025e+00, -4.9774e+00,  3.3973e+00,
          2.1625e+00,  2.2947e-01,  3.1486e+00, -1.7936e+00, -1.8790e+00,
          2.8723e+00, -2.1650e+00,  9.6802e-01,  1.3527e+00, -1.2992e+00,
          5.0146e-01,  1.0643e-01, -3.2138e+00, -4.7904e-01, -1.8417e+00,
         -1.2158e+00, -1.4134e+00, -2.3304e+00, -1.8468e+00, -1.0025e+00,
         -1.8345e-03, -2.3440e+00,  9.7086e-01,  4.5544e-01,  2.8649e+00,
         -2.4013e+00,  1.4181e+00, -1.3995e+00,  1.1271e+00,  7.2721e-01,
          6.5078e-01,  7.9881e-01,  1.9788e+00,  2.9911e-01, -2.2252e+00,
         -7.3543e-02,  2.2458e-01,  1.1003e-01,  4.5616e+00, -2.0423e+00,
          1.4514e+00, -5.4374e-01, -5.4203e-01, -1.3980e+00, -1.6925e+00,
          9.2412e-01,  2.2160e-01,  2.9389e+00, -3.7402e+00,  1.1879e-01,
          1.3919e+00,  5.8189e-01,  1.6937e+00, -3.4922e-01,  2.3588e+00,
          1.4474e+00,  9.2330e-01,  1.